#!/usr/bin/env bash
# scripts/gen-index.sh — regenerate the README progress block + cheatsheet.md
# from the on-disk commands/ tree. A node is "done" when its README lacks <!-- STUB -->.
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
CMD="$ROOT/commands"
README="$ROOT/README.md"
CHEAT="$ROOT/cheatsheet.md"

# All node README paths except the template, sorted by command path.
nodes() { find "$CMD" -mindepth 2 -name README.md -not -path "$CMD/_TEMPLATE/*" | sort; }

node_path() { sed "s|$CMD/||; s|/README.md||" <<<"$1"; }   # commands/pr/create/README.md -> pr/create
is_done()   { ! grep -q '<!-- STUB -->' "$1"; }
oneliner()  { sed -n 's/^> \*\*One-liner:\*\* //p' "$1" | head -1; }

# --- progress block (top-level groups only; promoted subs roll up) ------
# Portable: iterate immediate subdirs via a glob (no GNU `find -printf`).
progress() {
  echo "<!-- BEGIN PROGRESS (generated by scripts/gen-index.sh) -->"
  local total=0 ndone=0 d r mark
  for d in "$CMD"/*/; do
    r="$(basename "$d")"
    [[ "$r" == _* ]] && continue          # skip _TEMPLATE and other _meta dirs
    total=$((total+1)); mark=" "
    if [[ -f "$CMD/$r/README.md" ]] && is_done "$CMD/$r/README.md"; then mark="x"; ndone=$((ndone+1)); fi
    echo "- [$mark] $r"
  done
  echo
  echo "_Progress: $ndone / $total groups._"
  echo "<!-- END PROGRESS -->"
}

# Replace the marked block in README.md in place. Splice via a temp file —
# awk -v cannot carry a multi-line value ("newline in string").
pblock="$(mktemp)"; tmp="$(mktemp)"
progress > "$pblock"
awk -v f="$pblock" '
  /<!-- BEGIN PROGRESS/ { while ((getline l < f) > 0) print l; close(f); skip=1; next }
  /<!-- END PROGRESS -->/ { skip=0; next }
  !skip
' "$README" > "$tmp" && mv "$tmp" "$README"
rm -f "$pblock"
echo "updated $README"

# --- cheatsheet (one block per node, in command-path order) -------------
{
  echo "# gh cheatsheet"
  echo "<!-- GENERATED by scripts/gen-index.sh — do not edit. Edit the node READMEs instead. -->"
  echo
  for n in $(nodes); do
    p="$(node_path "$n")"; one="$(oneliner "$n")"
    if is_done "$n"; then echo "## gh ${p//\// }"; echo "${one:-_TODO_}"; echo
    else echo "## gh ${p//\// } _(stub)_"; echo; fi
  done
} > "$CHEAT"
echo "updated $CHEAT"
