#!/usr/bin/env bash
# scripts/scaffold.sh — generate/refresh the gh-mastery command tree from `gh` itself.
#
#   1. Discovers the live `gh` command tree → commands/_inventory.md
#   2. Creates a node (README/DRILLS/RECALL from _TEMPLATE/) for every command
#      group and every promotion listed in commands/_promotions.txt
#   3. Idempotent: never overwrites a node that already exists
#
# Re-run after a `gh` upgrade, then `git diff commands/_inventory.md` to see what's new.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CMD="$ROOT/commands"
TPL="$CMD/_TEMPLATE"
PROMO="$CMD/_promotions.txt"
INV="$CMD/_inventory.md"
EXCLUDE="co"   # built-in alias for `pr checkout`, not a real command group

# Parse a `gh ... --help` COMMANDS section into bare subcommand names.
subcommands() {  # args: gh path (none = top level), e.g. pr  |  repo deploy-key
  gh "$@" --help 2>/dev/null | awk '
    /^[A-Z][A-Z ]*COMMANDS/{f=1; next}
    /^[A-Z]/{f=0}
    f && /^[[:space:]]+[a-z]/ {sub(/:$/,"",$1); print $1}
  ' | sort -u
}

groups() { subcommands | grep -vxF "$EXCLUDE"; }

# Create a node from the template if it does not already exist. Idempotent.
make_node() {  # arg: path under commands/, e.g. pr  |  pr/create
  local rel="$1" dir="$CMD/$1"
  [[ -d "$dir" ]] && return 0
  mkdir -p "$dir"
  local label="${rel//\// }"          # pr/create -> "pr create"
  for f in README DRILLS RECALL; do
    sed "s|<group>|$label|g" "$TPL/$f.md" > "$dir/$f.md"
  done
  echo "created node: commands/$rel"
}

# 1. inventory (full live gh tree) ---------------------------------------
{
  echo "# gh command inventory — $(gh --version | head -1)"
  echo "<!-- GENERATED by scripts/scaffold.sh — do not edit. Re-run after a gh upgrade and diff. -->"
  echo
  for g in $(groups); do
    subs="$(subcommands "$g" | tr '\n' ' ')"
    echo "- **$g** — ${subs:-_(no subcommands)_}"
  done
} > "$INV"
echo "wrote $INV"

# 2. group nodes ---------------------------------------------------------
for g in $(groups); do make_node "$g"; done

# 3. promoted subcommand nodes -------------------------------------------
if [[ -f "$PROMO" ]]; then
  grep -vE '^[[:space:]]*(#|$)' "$PROMO" | while read -r rel; do make_node "$rel"; done
fi

echo "scaffold complete. Next: scripts/gen-index.sh"
